### ISSUE TITLE
Review Shiny CI/CD

### ISSUE THREAD

**Issue by riccardoporreca** [miraisolutions/techguides#14]
https://mirai-solutions.ch/techguides/cicd-pipelines-for-automatic-deployment-of-a-r-shiny-web-app.html does not reflect the current reality: the content was written when Travis was the well-established tool and Actions was the not-yet-mature one, which is not quite the current situation.

A review is needed to have the primary focus on Actions.

**Comment by Chargothrond** [comment]
See PR for the update and review of it: https://github.com/miraisolutions/techguides/pull/27
