### ISSUE TITLE
Possible typo in 1.4.3 : division or multiplication?

### ISSUE THREAD

**Issue by CorradoLanera** [miraisolutions/techguides#16]
https://github.com/miraisolutions/techguides/blob/5f0ffe41b84cda48785339908f4e8c904b43adfd/roxygen-guidelines/roxygenExPkg/R/divide_rdname.R#L28-L30

Should this operator be a `/`?

**Comment by riccardoporreca** [comment]
Thanks for reporting @CorradoLanera! 
This is indeed a typo, inherited from the `times()` example function, we'll fix it shortly.

**Comment by riccardoporreca** [comment]
Fixed in 5d2be972f22337111dc06704e65ee8357df5fba0
