### ISSUE TITLE
Location of option() statement when using {renv}.

### ISSUE THREAD

**Issue by CorradoLanera** [miraisolutions/techguides#17]
https://github.com/miraisolutions/techguides/blob/5f0ffe41b84cda48785339908f4e8c904b43adfd/renv.Rmd#L52-L74

That is a great suggestion! On the other hand, where do you put the `option()` statement? Are you using a project-level `.Rprofile` file tracked on GitHub?

**Comment by riccardoporreca** [comment]
@CorradoLanera, thanks for your question, and interest in techguides.

**renv** keeps track of the repository set in the `option()` when `renv::snapshot()` is called, as you can see in the generated `renv.lock` file. The repository in the lockfile is then set by **renv** itself upon activation, i.e. when starting a session for a project using renv.

So, long story short: if you set it when initializing renv as described in the techguides, and **renv** will persist the option for you!

You may want to look at how we are using this for our Covid19 Shiny app at [Covid19/renv/renv-setup.R](https://github.com/miraisolutions/Covid19/blob/16268be1d744887433285f4041782ce51f24b27b/renv/renv-setup.R). There, we actually cherry-pick newer package versions compared to a reference snapshot and have to adjust the `option(repos)` before creating the snapshot.

There are a lot of comments in the Covid19 file above explaining the setup more in detail, some of which I believe could be used to improve the techguides. We'll probably follow up on this!

**Comment by CorradoLanera** [comment]
Great! I didn’t know that! Thanks!
