### ISSUE TITLE
Cleanup renv exclusion

### ISSUE THREAD

**Issue by riccardoporreca** [miraisolutions/techguides#34]
We should not need to explicitly exclude the renv directory when deploying via `rsconnect`

https://github.com/miraisolutions/techguides/blob/aa4edf58212351d3902e70ae3758d361ea59d8e6/shiny-ci-cd/deploy/deploy-shinyapps.R#L10-L11

This was introduced in https://github.com/riccardoporreca/ShinyCICD/commit/6afa989b26b0c5b538fcf3659fa4cdc6e787ed51 and implicitly also excludes `.Rprofile`.

This is not necessary with recent versions of `rsconnect` via https://github.com/rstudio/rsconnect/pull/367 and  https://github.com/rstudio/rsconnect/pull/462

Simplification to be first tried in https://github.com/miraisolutions/ShinyCICD

**Comment by Chargothrond** [comment]
ShinyCICD PR: https://github.com/miraisolutions/ShinyCICD/pull/9
